"""change true to false for aitisimetadi

Revision ID: 045e4288379a
Revises: 41d11ec72c98
Create Date: 2024-07-24 20:05:00.009990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045e4288379a'
down_revision = '41d11ec72c98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('father_fullname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('mother_fullname',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('pdf_filename',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.alter_column('pdf_filename',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('birth_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('mother_fullname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('father_fullname',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
