"""2ndchoicefalse

Revision ID: 1c94932fab5e
Revises: 53b3dca82590
Create Date: 2024-07-22 12:52:20.694487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c94932fab5e'
down_revision = '53b3dca82590'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisi1_db', schema=None) as batch_op:
        batch_op.alter_column('second_choice',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisi1_db', schema=None) as batch_op:
        batch_op.alter_column('second_choice',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)

    # ### end Alembic commands ###
