"""Add Aistisimetadimotefsis_db table

Revision ID: 41d11ec72c98
Revises: 1c94932fab5e
Create Date: 2024-07-24 19:50:37.825358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d11ec72c98'
down_revision = '1c94932fab5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aitisimetadimotefsis_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=20), nullable=True),
    sa.Column('last_name', sa.String(length=20), nullable=True),
    sa.Column('father_fullname', sa.String(length=20), nullable=True),
    sa.Column('mother_fullname', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('pdf_filename', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('aitisimetadimotefsis_db')
    # ### end Alembic commands ###
