"""2ndchoice

Revision ID: 53b3dca82590
Revises: 
Create Date: 2024-07-22 12:51:31.010815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53b3dca82590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisi1_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('second_choice', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisi1_db', schema=None) as batch_op:
        batch_op.drop_column('second_choice')

    # ### end Alembic commands ###
