"""pdf dieti katikia change to False

Revision ID: b64a1cb46fda
Revises: ed67d98d1530
Create Date: 2024-08-01 12:32:27.535511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64a1cb46fda'
down_revision = 'ed67d98d1530'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.alter_column('pdf_dieti_katikia',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.alter_column('pdf_dieti_katikia',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###
