"""pdf dilosi epanadimotefsi

Revision ID: b65b8cb243bc
Revises: b64a1cb46fda
Create Date: 2024-08-02 11:44:24.791103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b65b8cb243bc'
down_revision = 'b64a1cb46fda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_dilosi_epanadimotefsi', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.drop_column('pdf_dilosi_epanadimotefsi')

    # ### end Alembic commands ###
