"""pdf dieti katikia

Revision ID: ed67d98d1530
Revises: 045e4288379a
Create Date: 2024-08-01 12:27:07.069393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed67d98d1530'
down_revision = '045e4288379a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdf_dieti_katikia', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('aitisimetadimotefsis_db', schema=None) as batch_op:
        batch_op.drop_column('pdf_dieti_katikia')

    # ### end Alembic commands ###
